theme: jekyll-theme-minimal
title: Kubernetes Hands-on
updated: 12.1.2023
description: Deploy a ToDo app on Kubernetes
show_downloads: False
navigation:
  - title: Overview, intial setup
    url: /
  - title: 1. Deploy ToDo app
    url: docs/lab1
  - title: 2. Deploy MySQL
    url: docs/lab2
  - title: 3. Connect ToDo with MySQL using Environment Variables
    url: docs/lab3
  - title: 4. MySQL with Persistent Volumes
    url: docs/lab4
  - title: 5. Connect ToDo with MySQL using ConfigMap
    url: docs/lab5
  - title: 6. Connect ToDo with MySQL using ConfigMap and Secret
    url: docs/lab6

